ALTER TABLE "AiCallLog" ADD COLUMN "inputTokens" INTEGER;
ALTER TABLE "AiCallLog" ADD COLUMN "outputTokens" INTEGER;
ALTER TABLE "AiCallLog" ADD COLUMN "totalTokens" INTEGER;
ALTER TABLE "AiCallLog" ADD COLUMN "imageCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AiCallLog" ADD COLUMN "estimatedCostUsd" DECIMAL(12, 6);
