ALTER TABLE "Grinder" ADD COLUMN IF NOT EXISTS "locationName" TEXT;
ALTER TABLE "Grinder" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Grinder" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;

ALTER TABLE "Brewer" ADD COLUMN IF NOT EXISTS "locationName" TEXT;
ALTER TABLE "Brewer" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Brewer" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
